# Generated by Django 5.0.8 on 2024-08-12 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productgallary'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductGallary',
            new_name='ProductGallery',
        ),
    ]
