# Generated by Django 5.0.8 on 2024-08-12 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_rename_productgallary_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'product gallerys', 'verbose_name_plural': 'product gallery'},
        ),
    ]
